repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true

    -   id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args: [--check]

    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true

